version: '3.8'

services:
  app:
    image: civic-bot-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "5173:5173"  # Map port 5173 in the container to port 5173 on the host
    command: npm run dev  # Start the development server
    working_dir: /app  # Set the working directory