version: '3.8'

services:
  app:
    image: civic-bot-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"  # Map port 5173 in the container to port 5173 on the host
    working_dir: /app  # Set the working directory